name: Build and Deploy

on:
  pull_request:
  push:
    paths:
    - '.github/workflows/deploy.yml'
    - 'config.toml'
    - 'content/**'
    - 'resources/**'
    - 'static/**'
    - 'themes/temple'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-artifact-name: ${{ steps.upload.outputs.foo }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Hugo build
      run: hugo --minify

    - name: Upload build result
      id: upload
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: public
      run: echo 'also run'

  deploy-to-s3:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    # References to the env context aren't supported here, so copy-paste from
    # the definition of DO_DEPLOY.
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - name: Download build result
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: public

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: aws s3 sync --delete public s3://ravron.com

  invalidate-cloudfront:
    name: Invalidate CloudFront
    runs-on: ubuntu-latest
    needs: deploy-to-s3
    steps:
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id E3UK5EPKDEOBYZ \
          --paths '/*'
