name: Deploy the lambda@edge function

on:
  push:
    branches: [ master ]
    paths:
    - 'edge/**'
    - '.github/workflows/deploy-edge.yml'

defaults:
  run:
    working-directory: edge

jobs:
  deploy-cloudfront-viewer-response-function:
    name: Deploy Cloudfront function
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update Cloudfront viewer-response function
      run: |
        ETAG=$(aws cloudfront describe-function \
          --name ravron-com-viewer-response | \
          jq -r .ETag
        )
        aws cloudfront update-function \
          --name ravron-com-viewer-response \
          --if-match $ETAG \
          --function-config Comment="",Runtime="cloudfront-js-1.0" \
          --function-code fileb://viewer-response.js
    - name: Publish Cloudfront viewer-response function
      run: |
        ETAG=$(aws cloudfront describe-function \
          --name ravron-com-viewer-response | \
          jq -r .ETag
        )
        aws cloudfront publish-function \
          --name ravron-com-viewer-response \
          --if-match $ETAG
