name: Deploy the lambda@edge function

on:
  push:
    branches: [ master ]
    paths: [ 'edge/**' ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update function
      run: |
        cd edge
        zip cloudfront.zip cloudfront.py
        aws lambda update-function-code \
          --function-name arn:aws:lambda:us-east-1:015240938778:function:ravroncom-edge \
          --zip-file fileb://cloudfront.zip \
          --publish | \
          jq -r .FunctionArn > function-arn.txt
        echo 'Updated function to ' $(<function-arn.txt)
