name: Deploy to S3

on:
  push:
    # branches: [ master ]
    paths:
    - '.github/workflows/deploy.yml'
    - 'config.toml'
    - 'content/**'
    - 'resources/**'
    - 'static/**'
    - 'themes/temple'

env:
  DO_DEPLOY: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Hugo build
      run: hugo --minify

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: public

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - run: echo '${{ github.ref }}'

    - name: Upload to S3
      if: false
      run: aws s3 sync --delete public s3://ravron.com

    - name: Invalidate CloudFront
      if: false
      run: |
        aws cloudfront create-invalidation \
          --distribution-id E3UK5EPKDEOBYZ \
          --paths '/*'
